compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  firstassethr:
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
